version: "3"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /docker/plex/config:/config
      - /home/robot/data/media/Television:/tv
      - /home/robot/data/media/Movies:/movies
    restart: unless-stopped